Correct checkbox/radio colors and add hover style.
moderntribe/tribe-common pull request #1435
Opened 2020-09-02 17:05 UTC by Camwyn

📷 http://p.tri.be/jSBkcH
[FBAR-165]

2020-09-02 18:24 UTC, paulmskim requested changes

2020-09-02 18:24 UTC, paulmskim commented on src/resources/postcss/base/full/forms/_checkboxes-radios.pcss
> +			opacity: .8;
We have a variable for opacity, let's use that. Also, `.tribe-common-form-control-radio` and `.tribe-common-form-control-checkbox` are divs, non-focusable by design. The `:hover` and `:focus` should be on a hoverable/focusable element, which would be the input.

2020-09-02 21:07 UTC, sc0ttkclark approved these changes

2020-09-03 02:53 UTC, paulmskim requested changes

2020-09-03 02:53 UTC, paulmskim commented on src/resources/postcss/base/full/forms/_checkboxes-radios.pcss
> +			}
this, when compiled, will create:

```
.tribe-common-form-control-checkbox__input:hover + .tribe-common-form-control-checkbox__label,
.tribe-common-form-control-checkbox__input:hover + .tribe-common-form-control-radio__label,
...
```

the checkbox input will never have a sibling radio label, and vice versa, and all we'd be doing is bloating our CSS. let's move the checkboxes to its own and radios to its own (see below).

2020-09-03 02:53 UTC, paulmskim commented on src/resources/postcss/base/full/forms/_checkboxes-radios.pcss
> +		}
i believe you'd get a double-hit on opacity with this, no? if you hover over the label, what happens?

2020-09-03 16:39 UTC, paulmskim approved these changes

2020-09-03 16:39 UTC, merged