Syntax update of arrays from `array()` to `[]`
moderntribe/tribe-common pull request #1501
Opened 2020-11-20 21:38 UTC by mitogh

2020-11-23 17:55 UTC, lucatume requested changes
Look into and fix the tests.

2020-11-24 10:34 UTC, paulmskim reviewed
a couple of odd indentations

2020-11-24 10:34 UTC, paulmskim commented on src/Tribe/Admin/Help_Page.php
> +		];
this file has weird indentation

2020-11-24 10:34 UTC, paulmskim commented on src/admin-views/tribe-options-help.php
> +], 10 );
indentation

2020-11-26 06:24 UTC, bordoni approved these changes

2020-11-26 06:25 UTC, bordoni requested changes
We need to make sure the syntax problems are resolved. Check tests.

2020-11-27 08:33 UTC, lucatume commented
Rebasing on `release/B20.12`.

2020-11-27 09:12 UTC, merged